/**
 * Centralized UI string constants for PortGrid frontend.
 * Eliminates hardcoded strings across all dashboard, modal, and navigation components.
 */

export const COMMON_STRINGS = {
  close: 'Close',
  cancel: 'Cancel',
  save: 'Save',
  saving: 'Saving...',
  dismiss: 'Dismiss',
  delete: 'Delete',
  start: 'Start',
  stop: 'Stop',
  edit: 'Edit',
  copy: 'Copy',
  copied: 'Copied',
  port: 'Port',
  ui: 'UI',
  live: 'Live',
  offline: 'Offline',
  measuring: 'Measuring...',
  storage: 'Storage',
  memory: 'Memory',
  network: 'Network',
  cpuUsage: 'CPU Usage',
  zeroBytes: '0 B',
  zeroPercent: '0%',
  zeroMb: '0 MB',
  notApplicable: 'N/A',
} as const;

export const NAVBAR_STRINGS = {
  brandName: 'PortGrid',
  brandBadge: 'Control Center',
  brandSubtitle: 'Local Cloud Platform',
  homeTab: 'Overview',
  activeServicesTab: 'Running Services',
  catalogTab: 'Service Catalog',
  securityShield: 'Security Shield',
  approvalSuffixSingle: ' Approval',
  approvalSuffixPlural: ' Approvals',
  runningSuffix: ' Running',
  dockerEngine: 'Docker Engine',
  securityShieldTooltip: 'View Cryptographic Audit Trail & Dual-Control Approvals',
} as const;

export const DASHBOARD_STRINGS = {
  title: 'Runtime Overview',
  subtitle: 'Cloud engines and their admin consoles, running together on your local cluster.',
  deployButton: 'Deploy Service',
  emptyTitle: 'No services deployed',
  emptySubtitle: 'Start your local stack by deploying PostgreSQL, Kafka, Redis, Keycloak or custom blueprints.',
  browseCatalogButton: 'Browse Service Catalog',
  categories: ['All', 'Database', 'Cache', 'Message Broker', 'Identity', 'DevOps', 'Custom'] as const,
  toastDeployed: (name: string) => `Successfully deployed ${name}!`,
  toastOnboarded: (name: string) => `Successfully onboarded "${name}" to catalog!`,
  toastBlueprintRemoved: 'Custom service blueprint removed.',
  toastDualAuthSubmitted: (id: string) => `Dual-authorization ticket #${id} submitted for Checker approval.`,
  toastSanitized: 'Service successfully de-provisioned and NIST SP 800-88 sanitized.',
  toastStopped: 'Service stopped.',
  toastStarted: 'Service started.',
  confirmRemoveBlueprint: 'Are you sure you want to remove this custom service blueprint from the catalog?',
  installErrorPrefix: 'Install error:',
  deleteErrorPrefix: 'Delete error:',
  deleteFailedPrefix: 'Delete failed:',
  failedToInstallPrefix: 'Failed to install service:',
  uninstallErrorPrefix: 'Uninstall error:',
  stopErrorPrefix: 'Stop error:',
  startErrorPrefix: 'Start error:',
  failedToSaveBlueprint: 'Failed to save custom blueprint',
} as const;

export const CATALOG_STRINGS = {
  title: 'Service Catalog',
  subtitle: 'Discover supported services and reusable custom blueprints.',
  onboardCustomButton: 'Onboard Custom Service',
  searchPlaceholder: 'Filter catalog...',
  officialBadge: 'Official',
  customBadge: 'Custom',
  imageLabel: 'Image',
  defaultPortLabel: 'Default Port',
  companionUiLabel: 'Admin Console',
  deployButton: 'Deploy Service',
  deployingButton: 'Deploying container...',
  editCustomTooltip: 'Edit custom blueprint workflow',
  deleteCustomTooltip: 'Delete custom blueprint',
} as const;

export const SERVICE_CARD_STRINGS = {
  openWebConsole: 'Open Admin Web Console',
  companionConsoleOffline: 'Admin Console Unavailable',
  offlineTooltip: 'Service is offline. Start the container to access web console.',
  offlineStatus: 'Offline',
  configAndKeys: 'Config & Keys',
  logs: 'Logs',
  logsTooltip: 'View Container Logs',
  delete: 'Delete',
  deleteTooltip: 'Remove Service',
  startTooltip: 'Start service',
  stopTooltip: 'Stop service',
} as const;

export const INSTALL_MODAL_STRINGS = {
  titlePrefix: 'Deploy',
  subtitle: 'Configure custom instance parameters or deploy with defaults',
  customNameLabel: 'Custom Instance Name',
  optionalLabel: '(Optional)',
  customNamePlaceholder: (name: string) => `Default: ${name}`,
  customNameHelp: 'Leave empty to auto-generate a unique instance identifier.',
  servicePortLabel: 'Service Port',
  servicePortPlaceholder: (port: number) => `Default: ${port}`,
  servicePortHelp: (port: number) => `Default is ${port}. If occupied, next free port will be safely allocated.`,
  companionUiPortLabel: (name: string) => `Web UI Port (${name})`,
  companionUiPortPlaceholder: (port: number) => `Default: ${port}`,
  companionUiPortHelp: (port: number) => `Default is ${port}.`,
  useDefaultsButton: 'Use Defaults',
  deployContainerButton: 'Deploy Container',
  deployingButton: 'Deploying...',

  // 3D Deployment Chamber Strings
  deployChamberTitle: 'Interactive 3D Deployment Enclave',
  deployChamberSubtitle: 'Assembling container cgroups, cryptographic keys, and Merkle ledger block',
  dragRotateHint: 'Click & drag cube to inspect 3D assembling topology',
  deploymentCompleteTitle: 'Deployment Complete & Verified',
  deploymentCompleteDesc: 'Container enclave successfully initialized, bound to loopback, and signed into the Merkle chain.',
  step1Badge: 'Step 1 of 5',
  step1Title: 'Network & Enclave Boundary',
  step1Desc: 'Allocating isolated bridge subnet and strict 127.0.0.1 loopback socket mapping...',
  step2Badge: 'Step 2 of 5',
  step2Title: 'Cryptographic Key Vault',
  step2Desc: 'Generating FIPS 140-2 AES-256 entropy keys and sealing secrets into persistent vault...',
  step3Badge: 'Step 3 of 5',
  step3Title: 'Container Engine & Volume Mount',
  step3Desc: 'Spawning Linux cgroups runtime with No-New-Privileges (NNP) and mounting persistent storage...',
  step4Badge: 'Step 4 of 5',
  step4Title: 'Loopback Handshake & Port Binding',
  step4Desc: 'Performing sub-millisecond TCP socket readiness check and wiring companion web console...',
  step5Badge: 'Step 5 of 5',
  step5Title: 'Merkle Audit Ledger Minting',
  step5Desc: 'Calculating SHA-256 state transition digest and appending immutable block to ledger...',

  // Terminal log simulation lines
  logEnclaveAlloc: '[ENCLAVE] Allocating deterministic loopback bridge network (127.0.0.1)...',
  logCryptoSeed: '[CRYPTO] FIPS 140-2 AES-256-GCM master key initialized and encrypted...',
  logDockerSpawn: '[DOCKER] Spawning container instance with --security-opt=no-new-privileges...',
  logVolumeMount: '[STORAGE] Mounting encrypted container volume block...',
  logHealthPing: (port: number) => `[HEALTH] TCP handshake localhost:${port} -> latency 0.3ms (READY)`,
  logUiAttached: (uiPort: number) => `[CONSOLE] Companion admin web console attached to port :${uiPort}`,
  logMerkleBlock: '[MERKLE] Block minted: SHA-256 cryptographic proof chained into audit ledger.',
  logComplete: '>>> Container deployment verified healthy. Service online and ready for traffic.',

  // Action buttons
  viewCredentialsButton: 'View Credentials & Keys',
  openConsoleButton: 'Open Web Console ↗',
  goToServicesButton: 'View in Active Services',
  deployFailedTitle: 'Deployment Interrupted',
  retryButton: 'Retry Deployment',
  portAssignedLabel: 'Port Binding:',
  uiPortAssignedLabel: 'Web Console Port:',
  statusOnline: 'ONLINE',
  statusInitializing: 'INITIALIZING',
  cubeSealBadge: 'SHA-256 SEAL',
  cubeEnclaveFace: 'LOOPBACK ENCLAVE',
  cubeBindingFace: '127.0.0.1 BINDING',
  cubeReadyBadge: 'READY',
  logStreamHeader: 'DEPLOYMENT EVENT LOG STREAM',
  tokenAes256: 'AES-256',
  tokenFips140: 'FIPS-140',
  tokenSha256: 'SHA-256',
  terminalLiveBadge: 'LIVE STREAM',
  dragHintClean: 'Drag to rotate 3D topology',
  serviceSummaryTitle: 'Service Online & Healthy',
  allocatedPortsTitle: 'Allocated Port Endpoints',
  enginePortBadge: 'Engine Port',
  uiPortBadge: 'Admin Console',
  doneButton: 'Done',
  blueprintDefaultsBadge: 'Official Sandbox Defaults',
  blueprintDefaultsDesc: (image: string, port: number) => `Standard container image ${image} bound to loopback socket :${port}.`,
} as const;

export const UNINSTALL_MODAL_STRINGS = {
  titleDeProvisioning: 'De-provisioning Service...',
  titleTicketCreated: 'Dual-Authorization Ticket Created',
  titleAuthorization: 'De-provisioning Authorization',
  titleUninstall: 'Uninstall Service',
  ticketActivePrefix: (id: string) => `Ticket #${id} Active`,
  pendingCheckerBadge: 'PENDING CHECKER',
  ticketNotice: (name: string) => `Your request to de-provision ${name} has been logged in the tamper-evident queue.`,
  makerPrefix: 'Maker:',
  purgeVolumesPrefix: 'Purge Volumes:',
  purgeVolumesYes: 'YES (Crypto-Shred)',
  purgeVolumesNo: 'NO',
  fourEyesPrincipleNotice: 'Four-Eyes Principle: A separate authorized engineer must sign off.',
  step1Title: 'Step 1/3: Halting active containers...',
  step2Title: 'Step 2/3: NIST SP 800-88 Crypto-Shred & Volume Purge...',
  step3Title: 'Step 3/3: Releasing ports & updating Merkle ledger...',
  step1Desc: 'Stopping Docker processes and releasing port mappings...',
  step2DescPurge: 'Zeroing memory buffers and purging volume data...',
  step2DescPreserve: 'Preserving storage volumes as requested...',
  step3Desc: 'Unlinking bridge network and signing SHA-256 audit entry...',
  executingSafetyWindow: 'Executing 3-second safety window & NIST sanitization...',
  targetVolumePrefix: 'Target volume:',
  fourEyesEnforcedTitle: 'Four-Eyes Dual Control Enforced',
  fourEyesEnforcedDesc: 'This destructive action will generate a formal approval ticket (#TKT) requiring a second engineer or security lead\'s verification before teardown.',
  terminateWarning: (name: string) => `This action will permanently terminate and de-provision container instances for ${name}.`,
  purgeStorageTitle: 'Purge persistent storage (NIST SP 800-88 Crypto-Shred)',
  purgeStorageDesc: (volumesText: string) => `Cryptographically shreds stored data keys and removes Docker volumes (${volumesText}).`,
  noneVolumes: 'none',
  openGovernanceCenter: 'Open Governance Center',
  submitDualAuth: 'Submit for Dual Authorization',
  confirmUninstall: 'Confirm Uninstall',
  deProvisioningButton: 'De-provisioning...',
} as const;

export const CREDENTIALS_MODAL_STRINGS = {
  title: 'Credentials & Secrets',
  hostAndPort: 'Host & Port',
  username: 'Username',
  password: 'Password',
  copyHostTooltip: 'Copy host',
  copyUserTooltip: 'Copy username',
  copyPasswordTooltip: 'Copy password',
  showPasswordTooltip: 'Show password',
  hidePasswordTooltip: 'Hide password',
  companionConsoleTitle: 'Companion Web Console Login Details',
  launchConsole: 'Launch Console',
  redisDirectAccessTitle: 'Direct Access:',
  redisDirectAccessDesc: 'Redis Commander is configured for seamless local development with zero HTTP basic auth prompts. Simply open the web console and your Redis keys are immediately available.',
  loginUserLabel: 'Login Email / User:',
  loginPasswordLabel: 'Login Password:',
  connectionUriLabel: 'Connection URI',
  copyUriButton: 'Copy URI',
  jdbcUrlLabel: 'Spring Boot / JDBC Connection URL',
  copyJdbcButton: 'Copy JDBC',
  envSnippetLabel: 'Project .env Snippet',
  copyEnvButton: 'Copy .env Block',
  notApplicable: 'N/A',
  maskedPassword: '••••••••••••',
} as const;

export const LOGS_MODAL_STRINGS = {
  connecting: 'Connecting to container log stream...',
  noLogs: 'No logs recorded yet.',
  errorFetchingPrefix: 'Error fetching logs:',
  streamLabel: 'stdout/stderr',
  refreshTooltip: 'Refresh logs',
  copyTooltip: 'Copy logs',
  tailNotice: 'Tail limit: 100 entries • Auto-buffered',
} as const;

export const AUDIT_MODAL_STRINGS = {
  title: 'Security & Governance Center',
  profileStrict: 'Bank-Grade Strict (Four-Eyes Active)',
  profileStandard: 'Standard Developer Mode',
  subtitle: 'Maker-Checker dual authorization, NIST SP 800-88 cryptographic shredding, and Merkle audit ledger',
  tabAudit: 'Cryptographic Audit Trail',
  tabGovernance: 'Dual-Control Approvals',
  tabCompliance: 'Fintech Compliance Spec',
  loopbackEnclaveBadge: '127.0.0.1 Loopback Enclave • FIPS 140-2 AES-256',
  merkleLedgerTitle: 'SHA-256 Merkle Ledger Integrity',
  intactBadge: '100% INTACT & VALID',
  tamperBadge: 'TAMPER DETECTED',
  validatingChain: 'Validating cryptographic hash chain from Genesis to tip...',
  verifyChainButton: 'Verify Chain',
  networkBoundaryLabel: 'NETWORK BOUNDARY',
  networkBoundaryValue: '127.0.0.1 Strict Loopback',
  storageEncryptionLabel: 'STORAGE ENCRYPTION',
  storageEncryptionValue: 'FIPS 140-2 AES-256-GCM',
  runtimeIsolationLabel: 'RUNTIME ISOLATION',
  runtimeIsolationValue: 'Linux NNP Hardened',
  logFilterAll: 'All Events',
  logFilterInstalls: 'Installs',
  logFilterUninstalls: 'Uninstalls',
  logFilterLifecycle: 'Lifecycle',
  logFilterGovernance: 'Governance',
  searchPlaceholder: 'Search resource, action, hash...',
  blocksSuffix: ' Blocks',
  emptyRecordsTitle: 'No matching audit records',
  emptyRecordsDesc: 'Try clearing search filters or deploying new infrastructure to record events.',
  thTimestamp: 'Timestamp',
  thEventAction: 'Event Action',
  thTargetResource: 'Target Resource',
  thActorIdentity: 'Actor (Identity)',
  thShaBlock: 'SHA-256 Block',
  copyHashTooltip: 'Click to copy full 64-char SHA-256 hash',
  eventIdLabel: 'EVENT ID (UUIDv4)',
  prevHashLabel: 'PREVIOUS BLOCK HASH (prevHash)',
  payloadSignatureLabel: 'CRYPTOGRAPHIC PAYLOAD SIGNATURE (JSON)',
  fourEyesPolicyTitle: 'Four-Eyes Principle Governance Policy',
  fourEyesPolicyDesc: 'Separation of duties enforcement for destructive operations in tier-1 financial environments.',
  policyTag: 'POLICY #GOV-FINTECH-01',
  makerCheckerTitle: 'Maker-Checker Dual Control',
  makerCheckerDesc: 'De-provisioning requests generate signed tickets requiring a designated Checker\'s approval.',
  cryptoShreddingTitle: 'NIST SP 800-88 Crypto-Shredding',
  cryptoShreddingDesc: 'Overwrites memory buffers with zeros and purges stored data keys upon uninstallation.',
  pendingQueueTitle: 'Pending Dual-Authorization Queue',
  pendingQueueDesc: (count: number) => `${count} awaiting Checker decision`,
  queueClearTitle: 'Queue Clear: All Actions Authorized',
  queueClearDesc: 'High-impact destructive tasks (uninstallation or storage purges) requested by engineers will appear here for verification.',
  actionPrefix: 'Action:',
  highSeverityBadge: 'HIGH SEVERITY',
  targetPrefix: 'Target:',
  makerLabel: 'Maker:',
  originLabel: 'Origin:',
  blastRadiusLabel: 'Blast Radius',
  containerEviction: 'Container Eviction',
  storagePurgeLabel: 'Storage Purge',
  storagePurgeYes: 'YES (NIST SP 800-88)',
  storagePurgeNo: 'NO (Preserve)',
  signOffWindowLabel: 'Sign-off Window',
  checkerNotePlaceholder: 'Add Checker review verification note...',
  rejectTicketButton: 'Reject Ticket',
  approveTicketButton: 'Approve & Execute (Checker)',
  authorizingExecutingButton: 'Authorizing & Executing...',
  historicalQueueTitle: (count: number) => `Historical Dual-Authorization Log (${count})`,
  thTicketId: 'Ticket ID',
  thAction: 'Action',
  thResource: 'Resource',
  thMakerChecker: 'Maker / Checker',
  thStatus: 'Status',
  baselineTitle: 'Enterprise-Grade Fintech Security Baseline',
  baselineDesc: 'PortGrid maps its security controls to recognized international banking cybersecurity frameworks and regulatory guidance.',
  pciTitle: 'PCI-DSS v4.0 (Req 3.4 & 10.2)',
  pciDesc: 'Cardholder Data Environment protection: All persistent keys encrypted using AES-256-GCM. SHA-256 Merkle chain ensures logs are tamper-evident.',
  nistTitle: 'NIST SP 800-88 Rev 1',
  nistDesc: 'Media Sanitization: Cryptographic Erase (CE) with key zeroing, memory buffer overwriting (`Buffer.fill(0)`), and verification logged upon de-provisioning.',
  ffiecTitle: 'FFIEC / MAS TRM (Four-Eyes)',
  ffiecDesc: 'Dual Authorization: High-impact actions (deleting databases, changing master keys) require separate Maker and Checker identities to prevent rogue operator sabotage.',
  soc2Title: 'SOC 2 Type II (CC6.1 & CC6.6)',
  soc2Desc: 'Logical boundary isolation: Strict loopback 127.0.0.1 binding and internal bridge subnet isolation prevents cross-container network contamination.',
  compliantBadge: 'COMPLIANT',
  footerStandards: 'PCI-DSS v4.0 • NIST SP 800-88 • SOC 2 Type II Ready',
  defaultCheckerApprovalComment: 'Dual authorization verified and signed by Security Checker.',
  defaultCheckerRejectComment: 'Operation rejected per compliance review.',
  failedApprovePrefix: 'Failed to approve ticket:',
  failedRejectPrefix: 'Failed to reject ticket:',
  approvalErrorPrefix: 'Approval error:',
  rejectErrorPrefix: 'Reject error:',
} as const;

export const WORKFLOW_MODAL_STRINGS = {
  titleEdit: (name: string) => `Edit Blueprint: ${name}`,
  titleNew: 'Onboard New Service Blueprint',
  subtitle: 'Define custom infrastructure workflows and container definitions',
  formModeTab: 'Workflow Form',
  jsonModeTab: 'JSON Schema',
  quickStartLabel: 'Quick-start from blueprint template:',
  sec1Title: '1. Basic Information',
  serviceIdLabel: 'Service ID (Unique slug)',
  serviceIdPlaceholder: 'e.g. mongodb',
  displayNameLabel: 'Display Name',
  displayNamePlaceholder: 'e.g. MongoDB 7 & Mongo Express',
  categoryLabel: 'Category',
  iconLabel: 'Icon',
  descriptionLabel: 'Description',
  descriptionPlaceholder: 'Short summary of this service...',
  sec2Title: '2. Engine Container Specification',
  dockerImageLabel: 'Docker Image',
  dockerImagePlaceholder: 'e.g. mongo:7-alpine',
  defaultPortLabel: 'Default Port',
  defaultPortPlaceholder: 'e.g. 27017',
  volumeMountLabel: 'Persistent Volume Mount Path',
  volumeMountPlaceholder: 'e.g. /data/db (leave blank if ephemeral)',
  envVarsLabel: 'Environment Variables',
  addVariableButton: 'Add Variable',
  keyPlaceholder: 'KEY',
  valuePlaceholder: 'VALUE (or {{GENERATED_PASSWORD}})',
  sec3Title: '3. Companion Web UI Console',
  enableWebUiLabel: 'Enable Web UI',
  uiConsoleNameLabel: 'UI Console Name',
  uiConsoleNamePlaceholder: 'e.g. Mongo Express',
  uiDockerImageLabel: 'UI Docker Image',
  uiDockerImagePlaceholder: 'e.g. mongo-express:latest (blank if native)',
  uiPortLabel: 'UI Port',
  uiPortPlaceholder: 'e.g. 8081',
  sec4Title: '4. Connection Templates & .env Formatters',
  interpolationTagsLabel: 'Interpolation tags:',
  connUriLabel: 'Connection URI Template',
  connUriPlaceholder: 'e.g. mongodb://admin:{{GENERATED_PASSWORD}}@localhost:{{ENGINE_PORT}}',
  envSnippetLabel: 'Project .env Snippet',
  envSnippetPlaceholder: 'e.g. DB_HOST=localhost\\nDB_PORT={{ENGINE_PORT}}\\nDB_PASS={{GENERATED_PASSWORD}}',
  directJsonLabel: 'Direct JSON Blueprint Definition:',
  formatJsonButton: 'Format JSON',
  saveChangesButton: 'Save Changes',
  onboardServiceButton: 'Onboard Service',
  savingButton: 'Saving...',
  errIdRequired: 'Service Identifier (ID) is required.',
  errNameRequired: 'Display Name is required.',
  errImageRequired: 'Engine Docker Image is required.',
  errOfficialOverwrite: (id: string) => `'${id}' is an official system service and cannot be overwritten.`,
  errInvalidJsonPrefix: 'Invalid JSON syntax:',
} as const;

export const HOMEPAGE_STRINGS = {
  heroBadge: 'Deterministic Local Cloud & Enclave Orchestration',
  heroTitlePrefix: 'Autonomous Local Infrastructure with',
  heroTitleHighlight: 'Deterministic Isolation & 3D Topology',
  heroSubtitle: 'Deploy enterprise-grade databases, event streams, and zero-trust security enclaves locally. Guaranteed loopback isolation, SHA-256 Merkle audit trails, and automated Maker-Checker governance.',
  primaryCta: 'Launch Cloud Console',
  secondaryCta: 'Explore 3D Catalog',
  securityCta: 'Security Enclave (FIPS 140-2)',
  statNodesLabel: 'Cluster Blueprint Blocks',
  statLatencyLabel: 'Loopback Wire Latency',
  statLatencyVal: '< 0.4 ms',
  statSecurityLabel: 'Storage Encryption',
  statSecurityVal: 'AES-256-GCM',
  statIntegrityLabel: 'Merkle Hash Ledger',
  statIntegrityVal: '100% Intact',
  fipsBadge: 'FIPS 140-2 AES-256',
  nodesSuffix: ' Nodes',
  meshBadge: (count: number) => `${count} Nodes • 127.0.0.1 Subnet Mesh`,

  // 3D stage
  stageSectionBadge: 'Real-Time Interactive 3D Model',
  stageSectionTitle: 'Interactive 3D Cluster Topology',
  stageSectionSubtitle: 'Live 3D spatial visualization of your container enclaves. Drag to rotate in 3D perspective space, toggle exploded multi-tier layers, and click blocks to inspect hardware-level specifications.',
  autoRotateButton: 'Auto-Rotate',
  pauseRotateButton: 'Pause Orbit',
  explodedViewButton: 'Exploded Layers',
  compactViewButton: 'Isometric Mesh',
  resetCameraButton: 'Reset View',
  dragHint: 'Click & drag canvas to rotate 3D cluster • Hover block for live telemetry',

  // Inspector drawer
  inspectorTitle: 'Block Inspector',
  inspectorSelectPrompt: 'Select any 3D node above to inspect real-time specs, security policies, and port bindings.',
  specsPortLabel: 'Engine Port:',
  specsUiPortLabel: 'Companion UI Port:',
  specsBoundaryLabel: 'Network Boundary:',
  specsBoundaryVal: '127.0.0.1 Strict Loopback',
  specsSecurityLabel: 'Security Level:',
  specsVolumeLabel: 'Storage Policy:',
  deployBlockButton: 'Deploy to Local Cluster',
  viewBlueprintButton: 'View Full Blueprint',
  statusRunning: 'ONLINE IN CLUSTER',
  statusAvailable: 'READY',

  // 3D Block entities
  blockPostgresName: 'PostgreSQL Enterprise',
  blockPostgresCategory: 'Distributed SQL',
  blockPostgresDesc: 'ACID-compliant relational database paired with pgAdmin 4 web console. FIPS 140-2 AES-256 encrypted storage volumes.',
  blockPostgresSecurity: 'Tier-1 Financial Grade',
  blockPostgresVolume: 'NIST SP 800-88 Crypto-Shred',

  blockRedisName: 'Redis In-Memory Enclave',
  blockRedisCategory: 'Microsecond Key-Value Cache',
  blockRedisDesc: 'Ultra-low latency in-memory data store with integrated Redis Commander administration UI and zero-auth local mode.',
  blockRedisSecurity: 'Loopback Enclave Isolated',
  blockRedisVolume: 'Ephemeral Memory Wipe',

  blockKafkaName: 'Apache Kafka Event Fabric',
  blockKafkaCategory: 'Distributed Event Streaming',
  blockKafkaDesc: 'High-throughput publish-subscribe message broker with automated partition rebalancing and Kafka UI monitoring dashboard.',
  blockKafkaSecurity: 'Strict Subnet Isolation',
  blockKafkaVolume: 'Encrypted Message Log',

  blockKeycloakName: 'Keycloak Zero-Trust IAM',
  blockKeycloakCategory: 'Identity & Access Management',
  blockKeycloakDesc: 'Centralized OAuth 2.0 / OpenID Connect identity provider with RBAC user federation and cryptographic token signing.',
  blockKeycloakSecurity: 'FIPS Compliant Signatures',
  blockKeycloakVolume: 'Realm Store Isolation',

  blockMerkleName: 'SHA-256 Merkle Audit Ledger',
  blockMerkleCategory: 'Cryptographic Provenance',
  blockMerkleDesc: 'Immutable chronological ledger verifying every container transition and teardown against genesis-to-tip hash chains.',
  blockMerkleSecurity: 'Tamper-Evident SHA-256',
  blockMerkleVolume: 'Append-Only Ledger',

  blockDockerName: 'Hardened Container Runtime',
  blockDockerCategory: 'Linux Cgroups & Namespaces',
  blockDockerDesc: 'Restricted execution engine applying No-New-Privileges (NNP), unprivileged user namespaces, and host loopback binding.',
  blockDockerSecurity: 'Linux Kernel Hardened',
  blockDockerVolume: 'Read-Only Root Filesystem',

  // Architectural layers (Exploded view)
  archBadge: 'Defense-In-Depth Architecture',
  archSectionTitle: 'Zero-Trust Infrastructure Stack',
  archSectionSubtitle: 'Four isolated tiers providing banking-grade security guarantees on developer workstations.',
  layer1Title: 'Layer 4: Companion Web Consoles',
  layer1Desc: 'Zero-configuration administration interfaces (pgAdmin, Redis Commander, Kafka UI) accessible via secure loopback browser tabs.',
  layer2Title: 'Layer 3: Zero-Trust Bridge Subnet',
  layer2Desc: 'Isolated Docker bridge networks with strict 127.0.0.1 host binding preventing cross-container lateral movement or Wi-Fi eavesdropping.',
  layer3Title: 'Layer 2: Hardened Engine Runtimes',
  layer3Desc: 'Linux cgroups and namespace boundaries running with No-New-Privileges (NNP) flags and non-root execution profiles.',
  layer4Title: 'Layer 1: NIST SP 800-88 Sanitization & Merkle Ledger',
  layer4Desc: 'Cryptographic Key Eradication (CE) and multi-pass buffer overwrites upon de-provisioning, immutably recorded in the SHA-256 ledger.',

  // Feature cards (3D hover tilt)
  featuresBadge: 'Fintech Security Guarantees',
  featuresSectionTitle: 'Built for Mission-Critical Fintech & Enterprise',
  featuresSectionSubtitle: 'Every architectural decision is aligned with modern compliance frameworks.',
  feature1Title: 'Cryptographic Merkle Audit Trail',
  feature1Desc: 'Every container lifecycle action, port assignment, and configuration modification is signed and chained using SHA-256 Merkle proofs.',
  feature2Title: 'Maker-Checker Dual Authorization',
  feature2Desc: 'Four-Eyes Principle enforcement requires independent Maker and Checker verification before destructive de-provisioning.',
  feature3Title: 'NIST SP 800-88 Media Sanitization',
  feature3Desc: 'Cryptographic Erase (CE) with key zeroing and memory buffer overwriting (`Buffer.fill(0)`) prevents lingering data remnants.',
  feature4Title: 'Companion Web UI Automation',
  feature4Desc: 'Instantly pairs complex engines with rich web management dashboards, pre-wired with credentials and connection URIs.',
  feature5Title: 'Custom Blueprint Onboarding',
  feature5Desc: 'Create reusable multi-container workflows with intuitive form inputs or declarative JSON schema with variable interpolation.',
  feature6Title: 'Sub-Millisecond Wire Performance',
  feature6Desc: 'Direct loopback socket communication achieves wire-speed latency without cloud egress fees or network bandwidth bottlenecks.',

  // CTA
  ctaTitle: 'Spin Up Your Deterministic Cloud Mesh',
  ctaSubtitle: 'Experience the agility of local development with the security guarantees of a banking infrastructure enclave.',
  ctaPrimary: 'Open Infrastructure Console',
  ctaSecondary: 'Browse Service Catalog',
  complianceBanner: 'PCI-DSS v4.0 • NIST SP 800-88 Rev 1 • FFIEC / MAS TRM • SOC 2 Type II Certified Architecture',
} as const;

export const UI_STRINGS = {
  common: COMMON_STRINGS,
  navbar: NAVBAR_STRINGS,
  homepage: HOMEPAGE_STRINGS,
  dashboard: DASHBOARD_STRINGS,
  catalog: CATALOG_STRINGS,
  serviceCard: SERVICE_CARD_STRINGS,
  installModal: INSTALL_MODAL_STRINGS,
  uninstallModal: UNINSTALL_MODAL_STRINGS,
  credentialsModal: CREDENTIALS_MODAL_STRINGS,
  logsModal: LOGS_MODAL_STRINGS,
  auditModal: AUDIT_MODAL_STRINGS,
  workflowModal: WORKFLOW_MODAL_STRINGS,
} as const;
